### PR TITLE
Added Missing Comma 

### PR DESCRIPTION
**Pull request by UnrealApex**
I noticed there was a small typo that I did not catch in my previous pr.

### CODE REVIEW

**Comment by photopea** [comment]
Hi, could you please spell-check a text I wrote about myself?

Go to Photopea.com and press More - About Photopea.

**Comment by UnrealApex** [comment]
I am a bit busy this week, but I will try to when I get a chance.

**Comment by UnrealApex** [comment]
There appear to be no spelling errors but I do have some suggestions. If you wish, I could provide some feedback.

**Comment by photopea** [comment]
Sure, please, give me suggestions :)

**Comment by UnrealApex** [comment]
The main thing I would highly suggest would be adding more contractions, making the formality of the text sound more friendly and casual as you are talking about yourself. 

Here are some other ideas to better improve upon it: 
- what made you come up with the name Photopea besides the first domain was taken ?
-  detail more on why you are proud of your creation

### Revised Version

---
# About Me
### Hi there!
My name is Ivan Kutskir and I'm the creator of Photopea.

I'm a 30-year-old web developer based in the Czech Republic. I was born in Ukraine but now live in the Czech Republic.

I started developing Photopea back in 2012. I intended to call it Photo Hammer, but the domain was already taken so I had to come up with a different name.

My friends and family didn't know about Photopea during the first four years of development, I was spending a lot of time developing it, without making any money or learning anything new. So nothing to be proud of, but the project was fun and I enjoyed working on it. 

Now, it's heartwarming to know that millions around the world use Photopea as their creative medium. To this day I work on Photopea, driven by the positive impact of my creation. 

Ivan Kutskir
support@photopea.com

**Comment by photopea** [comment]
I modified the text a bit, thanks a lot! :)

I chose Photopea.com because I accidentally found this domain to be not taken, while it was quite short. I think it is not a very interesting story.

I am proud of Photopea mainly because it useful to so many people.

**Comment by DevBadger10** [comment]
> I modified the text a bit, thanks a lot! :)
> 
> I chose Photopea.com because I accidentally found this domain to be not taken, while it was quite short. I think it is not a very interesting story.
> 
> I am proud of Photopea mainly because it useful to so many people.

I love the story of how it came into existence! I'm so glad I found this, as I almost never read About pages! It's amazing how far it's came! Now that I know the story, I feel a lot better while using PhotoPea.

**Pull request merged**
