### PR TITLE
Add issue templates

### PR DESCRIPTION
**Pull request by DevBadger10**
I think these'd be useful as it adds abilities for people to know exactly what is expected for issues.

### CODE REVIEW

**Comment by photopea** [comment]
I think it makes reporting a bug too complicated for the average user :(

**Comment by DevBadger10** [comment]
Hmmmm..... let me see what I can do.

**Comment by DevBadger10** [comment]
I think it would be nice if GitHub had a bit more customization for it, like you being able to mount it to the side of the screen and it, by default, showing a blank issue.

OK, I've made it a bit more user-friendly. If you link to the Template Link, then people should find it easier to report bugs. An example of the template link is https://github.com/DevBadger10/photopea/issues/new?assignees=&labels=bug&template=bug_report.md&title=BR%3A+

**Comment by DevBadger10** [comment]
I personally think thata athe current issue sceme is OK. I'll cancel this request.

**Pull request closed without merging**
